---
apiVersion: v1
kind: Namespace
metadata:
  name: craq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goredis
  namespace: craq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goredis
  template:
    metadata:
      namespace: craq
      labels:
        app: goredis
    spec:
      containers:
        - name: goserver
          image: goserver
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
